-- CREAMOS LA BASE DE DATOS
CREATE DATABASE gestion_usuarios;

-- A CONTINUACIÓN, SELECCIONAMOS LA BASE DE DATOS A UTILIZAR
USE gestion_usuarios;

-- EN ÚLTIMO LUGAR, CREAMOS LA TABLA DE PERFILES DEL USUARIO
CREATE TABLE perfil_usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    puntos_acumulados INT DEFAULT 0
);
